#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libksysguard
Version  : 5.16.2
Release  : 21
URL      : https://github.com/KDE/libksysguard/archive/v5.16.2/libksysguard-5.16.2.tar.gz
Source0  : https://github.com/KDE/libksysguard/archive/v5.16.2/libksysguard-5.16.2.tar.gz
Summary  : Libraries for ksysguard
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: libksysguard-data = %{version}-%{release}
Requires: libksysguard-lib = %{version}-%{release}
Requires: libksysguard-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : kglobalaccel-dev
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86misc-dev libXxf86vm-dev
BuildRequires : plasma-framework-dev
BuildRequires : qtbase-dev mesa-dev
BuildRequires : qtwebengine-dev
BuildRequires : zlib-dev

%description
To create a script:
* Make a folder here with any name
* Inside create a file with any name, ending .desktop, looking like:

%package data
Summary: data components for the libksysguard package.
Group: Data

%description data
data components for the libksysguard package.


%package dev
Summary: dev components for the libksysguard package.
Group: Development
Requires: libksysguard-lib = %{version}-%{release}
Requires: libksysguard-data = %{version}-%{release}
Provides: libksysguard-devel = %{version}-%{release}
Requires: libksysguard = %{version}-%{release}
Requires: libksysguard = %{version}-%{release}

%description dev
dev components for the libksysguard package.


%package lib
Summary: lib components for the libksysguard package.
Group: Libraries
Requires: libksysguard-data = %{version}-%{release}
Requires: libksysguard-license = %{version}-%{release}

%description lib
lib components for the libksysguard package.


%package license
Summary: license components for the libksysguard package.
Group: Default

%description license
license components for the libksysguard package.


%prep
%setup -q -n libksysguard-5.16.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1561477697
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1561477697
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libksysguard
cp COPYING %{buildroot}/usr/share/package-licenses/libksysguard/COPYING
cp COPYING.LIB %{buildroot}/usr/share/package-licenses/libksysguard/COPYING.LIB
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
/usr/lib64/libexec/kauth/ksysguardprocesslist_helper

%files data
%defattr(-,root,root,-)
/usr/share/dbus-1/system-services/org.kde.ksysguard.processlisthelper.service
/usr/share/dbus-1/system.d/org.kde.ksysguard.processlisthelper.conf
/usr/share/ksysguard/scripts/README
/usr/share/ksysguard/scripts/smaps/helper.js
/usr/share/ksysguard/scripts/smaps/index.html
/usr/share/ksysguard/scripts/smaps/main.js
/usr/share/ksysguard/scripts/smaps/smaps.desktop
/usr/share/ksysguard/scripts/smaps/sorttable.js
/usr/share/ksysguard/scripts/smaps/style.css
/usr/share/polkit-1/actions/org.kde.ksysguard.processlisthelper.policy
/usr/share/xdg/libksysguard.categories

%files dev
%defattr(-,root,root,-)
/usr/include/ksysguard/ksgrd/SensorAgent.h
/usr/include/ksysguard/ksgrd/SensorClient.h
/usr/include/ksysguard/ksgrd/SensorManager.h
/usr/include/ksysguard/ksgrd/SensorShellAgent.h
/usr/include/ksysguard/ksgrd/SensorSocketAgent.h
/usr/include/ksysguard/ksignalplotter.h
/usr/include/ksysguard/lsof.h
/usr/include/ksysguard/processcore/process.h
/usr/include/ksysguard/processcore/processes.h
/usr/include/ksysguard/processui/KTextEditVT.h
/usr/include/ksysguard/processui/ProcessFilter.h
/usr/include/ksysguard/processui/ProcessModel.h
/usr/include/ksysguard/processui/ksysguardprocesslist.h
/usr/lib64/cmake/KF5SysGuard/KF5SysGuardConfig.cmake
/usr/lib64/cmake/KF5SysGuard/KF5SysGuardConfigVersion.cmake
/usr/lib64/cmake/KF5SysGuard/KF5SysGuardLibraryTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5SysGuard/KF5SysGuardLibraryTargets.cmake
/usr/lib64/libksgrd.so
/usr/lib64/libksignalplotter.so
/usr/lib64/liblsofui.so
/usr/lib64/libprocesscore.so
/usr/lib64/libprocessui.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libksgrd.so.5.16.2
/usr/lib64/libksgrd.so.7
/usr/lib64/libksignalplotter.so.5.16.2
/usr/lib64/libksignalplotter.so.7
/usr/lib64/liblsofui.so.5.16.2
/usr/lib64/liblsofui.so.7
/usr/lib64/libprocesscore.so.5.16.2
/usr/lib64/libprocesscore.so.7
/usr/lib64/libprocessui.so.5.16.2
/usr/lib64/libprocessui.so.7

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libksysguard/COPYING
/usr/share/package-licenses/libksysguard/COPYING.LIB
